Settings:
    'run': 'Exp' # specify key from Experiments or 'All'
Experiments:
    'Exp':
        'control': "Cond B" # if not specified: first row conditions is used
        'conditions': ["Cond A", "Cond B", "Cond C"]