settings:
    'model': '/gpfs/soma_fs/home/boeger/PpaPred_builder/ML/XGBBestModel_35727184_20240515/XGBBestModel_20240515.pickle'
    'ASpath': '/gpfs/soma_fs/home/boeger/data/builder/new_features/dataset_cluster/20240514_Clustering00_6clusters/Preprocessing.pickle'
    'fbfill': 30
    'fps': 30
    'skip_already': False
    'overwrite batch': True
path:
    'PharaGlow data': '/gpfs/soma_fs/scratch/src/boeger/data_gueniz/ErenBoeger_2024'
    'predictions': '/gpfs/soma_fs/scratch/src/boeger/PpaPred_eren_35727184/ErenBoeger2024_20240709' #ErenBoeger_2024
    'analysis': '/gpfs/soma_fs/home/boeger/PpaPred/'
    'with subfolders': True
analysis:
    'summaries': True # needed for batch analysis
    'ethograms': True
    'transitions': True
    'trajectories': True
plot_settings:
    'percentiles': (0,100)
    'showfliers': False
    'bonferroni': True
    'Z': None
    'test_metrics': ['rel time in', 'mean duration','mean transitions','ethogram']
cluster_color:
  -1: '#dbdbdb'
  0: '#BB0A21'
  1: '#FF680A'
  2: '#ffa047'
  3: '#0B305E'
  4: '#6B0F67'
  5: '#a24d91'
# https://coolors.co//dbdbdb-BB0A21-FF680A-ffa047-0B305E-6B0F67-a24d91
cluster_labels:
  -1: None
  0: pred. feed
  1: pred. bite 
  2: pred. search
  3: dwelling 
  4: roaming
  5: search


    