name: PpaPred                                                                                                                                                           
channels:                                                                                                                                                       
  - conda-forge                                                                                                                                                         
dependencies:                                                                                                                                                             
  - python=3.8.15
  - joblib=1.2.0
  - matplotlib=3.6.2
  - networkx=2.8.8
  - numba=0.57.0
  - numpy=1.23.5
  - pandas=1.5.0
  - PyYAML=6.0
  - scikit-learn=1.2.0
  - scipy=1.10.1
  - tqdm=4.65.0
  - PyWavelets=1.3.0
  - umap-learn=0.5.3
  - imbalanced-learn=0.9.1
  - hyperopt=0.2.7
  - xgboost=1.7.4
  - ipykernel
  - nbconvert